debugging DFTInterpolator
Still seeing that the output of DFTInterpolator is not deterministic:
Here is repeated output of an example test that differs on different runs.

(desc-env-pip) kaya@fedora:~/Documents/project/DESC$ pytest -k test_singular_integral_vac_estell
/home/kaya/miniconda3/envs/desc-env-pip/lib/python3.12/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
=================================================== test session starts ===================================================
platform linux -- Python 3.12.0, pytest-8.3.4, pluggy-1.5.0
Matplotlib: 3.9.3
Freetype: 2.6.1
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/kaya/Documents/project/DESC
configfile: setup.cfg
plugins: typeguard-2.13.3, jaxtyping-0.2.28, split-0.8.2, mpl-0.16.1, monitor-1.6.6, cov-5.0.0, benchmark-4.0.0, nbmake-1.5.3
collected 844 items / 843 deselected / 1 selected

tests/test_integrals.py F                                                                                           [100%]

======================================================== FAILURES =========================================================
___________________________________ TestSingularities.test_singular_integral_vac_estell ___________________________________

self = <tests.test_integrals.TestSingularities object at 0x7f6cf125db20>

    @pytest.mark.unit
    def test_singular_integral_vac_estell(self):
        """Test calculating Bplasma for vacuum estell, which should be near 0."""
        eq = get("ESTELL")
        grid = LinearGrid(M=25, N=25, NFP=eq.NFP)
        keys = [
            "K_vc",
            "B",
            "|B|^2",
            "R",
            "phi",
            "Z",
            "e^rho",
            "n_rho",
            "|e_theta x e_zeta|",
        ]
        data = eq.compute(keys, grid=grid)
        k = min(grid.num_theta, grid.num_zeta * grid.NFP)
        s = k - 1
        q = k // 2 + int(np.sqrt(k))
        interpolator = DFTInterpolator(grid, grid, s, q)
        Bplasma = virtual_casing_biot_savart(data, data, interpolator, loop=True)
        # need extra factor of B/2 bc we're evaluating on plasma surface
        Bplasma += data["B"] / 2
        Bplasma = np.linalg.norm(Bplasma, axis=-1)
        # scale by total field magnitude
        B = Bplasma / np.linalg.norm(data["B"], axis=-1).mean()
>       np.testing.assert_allclose(B, 0, atol=0.005)

tests/test_integrals.py:675:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_allclose.<locals>.compare at 0x7f6cf139d580>, array([0.26020428, 0.25978221, 0.25833294, ..., 0.25034399, 0.25539644,
       0.25843631]), array(0))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=0.005', 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError:
E           Not equal to tolerance rtol=1e-07, atol=0.005
E
E           Mismatched elements: 2601 / 2601 (100%)
E           Max absolute difference: 0.45300952
E           Max relative difference: inf
E            x: array([0.260204, 0.259782, 0.258333, ..., 0.250344, 0.255396, 0.258436])
E            y: array(0)

../../../miniconda3/envs/desc-env-pip/lib/python3.12/contextlib.py:81: AssertionError
================================================= short test summary info =================================================
FAILED tests/test_integrals.py::TestSingularities::test_singular_integral_vac_estell - AssertionError:
=========================================== 1 failed, 843 deselected in 17.49s ============================================
(desc-env-pip) kaya@fedora:~/Documents/project/DESC$ pytest -k test_singular_integral_vac_estell
/home/kaya/miniconda3/envs/desc-env-pip/lib/python3.12/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
=================================================== test session starts ===================================================
platform linux -- Python 3.12.0, pytest-8.3.4, pluggy-1.5.0
Matplotlib: 3.9.3
Freetype: 2.6.1
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/kaya/Documents/project/DESC
configfile: setup.cfg
plugins: typeguard-2.13.3, jaxtyping-0.2.28, split-0.8.2, mpl-0.16.1, monitor-1.6.6, cov-5.0.0, benchmark-4.0.0, nbmake-1.5.3
collected 844 items / 843 deselected / 1 selected

tests/test_integrals.py F                                                                                           [100%]

======================================================== FAILURES =========================================================
___________________________________ TestSingularities.test_singular_integral_vac_estell ___________________________________

self = <tests.test_integrals.TestSingularities object at 0x7fb16b450e90>

    @pytest.mark.unit
    def test_singular_integral_vac_estell(self):
        """Test calculating Bplasma for vacuum estell, which should be near 0."""
        eq = get("ESTELL")
        grid = LinearGrid(M=25, N=25, NFP=eq.NFP)
        keys = [
            "K_vc",
            "B",
            "|B|^2",
            "R",
            "phi",
            "Z",
            "e^rho",
            "n_rho",
            "|e_theta x e_zeta|",
        ]
        data = eq.compute(keys, grid=grid)
        k = min(grid.num_theta, grid.num_zeta * grid.NFP)
        s = k - 1
        q = k // 2 + int(np.sqrt(k))
        interpolator = DFTInterpolator(grid, grid, s, q)
        Bplasma = virtual_casing_biot_savart(data, data, interpolator, loop=True)
        # need extra factor of B/2 bc we're evaluating on plasma surface
        Bplasma += data["B"] / 2
        Bplasma = np.linalg.norm(Bplasma, axis=-1)
        # scale by total field magnitude
        B = Bplasma / np.linalg.norm(data["B"], axis=-1).mean()
>       np.testing.assert_allclose(B, 0, atol=0.005)

tests/test_integrals.py:675:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_allclose.<locals>.compare at 0x7fb16b97dda0>, array([0.3662026 , 0.25978221, 1.45680712, ..., 0.25034399, 0.25539644,
       0.25843631]), array(0))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=0.005', 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError:
E           Not equal to tolerance rtol=1e-07, atol=0.005
E
E           Mismatched elements: 2601 / 2601 (100%)
E           Max absolute difference: 3.92344324
E           Max relative difference: inf
E            x: array([0.366203, 0.259782, 1.456807, ..., 0.250344, 0.255396, 0.258436])
E            y: array(0)

../../../miniconda3/envs/desc-env-pip/lib/python3.12/contextlib.py:81: AssertionError
================================================= short test summary info =================================================
FAILED tests/test_integrals.py::TestSingularities::test_singular_integral_vac_estell - AssertionError:
=========================================== 1 failed, 843 deselected in 17.47s ============================================
(desc-env-pip) kaya@fedora:~/Documents/project/DESC$